create table public.category (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  category_name text not null,
  parent_category_id bigint null,
  is_active boolean not null default true,
  constraint category_pkey primary key (id),
  constraint category_parent_category_id_fkey foreign KEY (parent_category_id) references category (id)
) TABLESPACE pg_default;
